
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hexadecimal", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hexadecimal {


    /**
     * 
     * @param valor
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decimalParaHexa", targetNamespace = "http://control/", className = "cliente.DecimalParaHexa")
    @ResponseWrapper(localName = "decimalParaHexaResponse", targetNamespace = "http://control/", className = "cliente.DecimalParaHexaResponse")
    @Action(input = "http://control/Hexadecimal/decimalParaHexaRequest", output = "http://control/Hexadecimal/decimalParaHexaResponse")
    public String decimalParaHexa(
        @WebParam(name = "valor", targetNamespace = "")
        int valor);

}
