
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HexadecimalService", targetNamespace = "http://control/", wsdlLocation = "http://localhost:40000/hexadecimal?wsdl")
public class HexadecimalService
    extends Service
{

    private final static URL HEXADECIMALSERVICE_WSDL_LOCATION;
    private final static WebServiceException HEXADECIMALSERVICE_EXCEPTION;
    private final static QName HEXADECIMALSERVICE_QNAME = new QName("http://control/", "HexadecimalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:40000/hexadecimal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEXADECIMALSERVICE_WSDL_LOCATION = url;
        HEXADECIMALSERVICE_EXCEPTION = e;
    }

    public HexadecimalService() {
        super(__getWsdlLocation(), HEXADECIMALSERVICE_QNAME);
    }

    public HexadecimalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEXADECIMALSERVICE_QNAME, features);
    }

    public HexadecimalService(URL wsdlLocation) {
        super(wsdlLocation, HEXADECIMALSERVICE_QNAME);
    }

    public HexadecimalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEXADECIMALSERVICE_QNAME, features);
    }

    public HexadecimalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HexadecimalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Hexadecimal
     */
    @WebEndpoint(name = "HexadecimalPort")
    public Hexadecimal getHexadecimalPort() {
        return super.getPort(new QName("http://control/", "HexadecimalPort"), Hexadecimal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hexadecimal
     */
    @WebEndpoint(name = "HexadecimalPort")
    public Hexadecimal getHexadecimalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://control/", "HexadecimalPort"), Hexadecimal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEXADECIMALSERVICE_EXCEPTION!= null) {
            throw HEXADECIMALSERVICE_EXCEPTION;
        }
        return HEXADECIMALSERVICE_WSDL_LOCATION;
    }

}
